### ISSUE TITLE
Erro in find if send a query with HTML encoded string and one "

### ISSUE THREAD

**Issue by albertosouza** [balderdashy/sails-mysql#153]
It seems to only happen in `sails-mysql`.

In a `new app` with one model `post` ( sails generate api post ) and one attribute `body`

Example url:
> http://localhost:1337/post?where=%7B"body"%3A%7B"contains"%3A"teste%5C""%7D%7D&sort=createdAt+desc

It use the unescaped string with " and @particlebanana i think this may allow a sql injection ...

```
// post model for test:
module.exports = {
  schema: true,
  attributes: {
    // post content
    body: {
      type: 'text',
      required: true
    }
  }
};
```

**Comment by Dallas62** [comment]
Can't reproduce, do you have a stack trace or some thing?

**Comment by albertosouza** [comment]
I tested creating a project with the sails 0.10.rc5 and the problem is not appearing more so I will close the issue

test project: https://github.com/albertosouza/sails-mysql-issue-153-test
