### ISSUE TITLE
Model.destroy() eventually deletes all table rows in many-to-many associations

### ISSUE THREAD

**Issue by erkstruwe** [balderdashy/sails-mysql#174]
Hi!

Unfortunately I don't have time to construct a dedicated example. But when I do e.g. `Offer.destroy({merchant: 1}).exec(console.log)` and Offer has a many-to-many association to ShippingCondition and the result set of the first query is empty, then it does this:

    2909 Query	SELECT `offer`..... FROM `offer` AS `offer`  WHERE `offer`.`merchant` = 1  ORDER BY `offer`.`id` DESC
    2909 Query	DELETE `offer` FROM `offer` AS `offer`  WHERE `offer`.`merchant` = 1
    2909 Query	SELECT `offer_shippingconditions__shippingcondition_offers`...... FROM `offer_shippingconditions__shippingcondition_offers` AS `offer_shippingconditions__shippingcondition_offers`   ORDER BY `offer_shippingconditions__shippingcondition_offers`.`id` DESC
    2909 Query	DELETE `offer_shippingconditions__shippingcondition_offers` FROM `offer_shippingconditions__shippingcondition_offers` AS `offer_shippingconditions__shippingcondition_offers`

The last query obviously deletes the whole join table which usually is a very bad thing. Please note that this only happens if the result set of the first query is empty.

**Comment by devinivy** [comment]
Is it simply missing a where clause?  Could this be the culprit in waterline-sequel? https://github.com/balderdashy/waterline-sequel/blob/b53d72df60eb9d9b060c56fc3cc272bf7b8578ca/sequel/index.js#L194

**Comment by erkstruwe** [comment]
It seems to be an issue in Waterline. There are several related issues there. One of them: https://github.com/balderdashy/waterline/issues/799

**Comment by devinivy** [comment]
@erkstruwe does it seem to be the case that this only happens when you attempt to delete a nonexistent record?

**Comment by erkstruwe** [comment]
Yes, anytime a call to `find(criteria)` would return an empty array, a call to `destroy(criteria)` empties the join table.

**Comment by particlebanana** [comment]
Should be fixed in `0.10.17` thanks to https://github.com/balderdashy/waterline/pull/815
