### ISSUE TITLE
createEach doesn't execute

### ISSUE THREAD

**Issue by brandonsimpson** [balderdashy/sails-mysql#193]
I'm trying to insert sequential data into a mysql table, for example a list of items where the auto-increment ID is incremented based on the insert order of the records. It's important the items are entered into the db in order. So inserting items [one, two, three, four] should be inserted in sequence in the db and the auto-increment IDs reflect this as 1, 2, 3, 4 sequentially.

I have attempted this using the .createEach(array) function and it is seemingly completely ignored. Turning on query logging output you can see the .create() function is called in a loop, and according to my understanding, because these aren't being executed within an async.eachSeries and the waterline mysql connection is asynchronous, the queries execute whenever they have time to get executed, causing the records to be inserted out of order.

I'm not sure if the sails-mysql adapter is overriding the waterline default correctly or not. But I do know it won't execute as it is.

I was trying something like this:

```javascript
var inserts = [];

for (i = 0; i < 10; i++) {
	inserts.push({
		value: i,
	});
}

test.createEach(inserts)
	.catch(function(err) {
		throw err;
	});
```

**Comment by particlebanana** [comment]
Similar discussion here: https://github.com/balderdashy/sails-postgresql/issues/128

**Comment by brandonsimpson** [comment]
Is anyone actually using .createEach() with any success? It absolutely does not fire for me and re-routes to .create() somehow.

I've tracked it down to node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js line 213 where it is referencing `self.adapter.create(valuesObject.values, function(err, values){` and when that is changed to `self.adapter.createEach` it is called but obviously breaks because it wasn't meant to be run that way. So, it seems to me that this is prematurely in production code and not respecting a a synchronous loop of sequential inserts.

**Comment by devinivy** [comment]
Status of this?  I do know that waterline merged PR https://github.com/balderdashy/waterline/pull/795 which changes the waterline fallback for `createEach` to insert sequentially.

**Comment by brandonsimpson** [comment]
Ran an npm update and tested multiple times with 100 sequential inserts and it seems to be working now. Thanks!

**Comment by Crusader4Christ** [comment]
Validation fail in ONE row from 1000 leads to fails of insert at all. How can I avoid this?
