### ISSUE TITLE
Use sails-mysql with proxy

### ISSUE THREAD

**Issue by dooburt** [balderdashy/sails-mysql#198]
I'd like to be able to use sails-mysql with a proxy, so it can be used on services such-as Heroku:-

https://devcenter.heroku.com/articles/quotaguardstatic#accessing-a-mysql-database-using-socks-proxy-in-node-js

Currently, I can't see a way of accessing the connection object to do this. Do you have any suggestions, or am I missing something?

**Comment by devinivy** [comment]
At first glance, it seems like you should be able to use the `stream` config option when registering your mysql connection.  But let us know if does not work!  Building off the example you linked to:
```javascript
var sockConn = new SocksConnection(remote_options, sock_options);

waterline.initialize({
    connections: {
        mysqlDb: {
            adapter: 'mysql',
            user: 'yummy',
            password: 'candy',
            database: 'trinkets',
            stream:  sockConn
        }
    },
    adapters: {
        mysql: require('sails-mysql')
    }
});
```

**Comment by dooburt** [comment]
So, I gave it a try;

var Path = require('path'),
    url = require('url'),
    SocksConnection = require('socksjs');

// https://devcenter.heroku.com/articles/quotaguardstatic#accessing-a-mysql-database-using-socks-proxy-in-node-js
var proxy = url.parse(process.env.QUOTAGUARDSTATIC_URL || 'http://xxx:yyy@us-east-1-static-brooks.quotaguard.com:9293');
var auth = proxy.auth;
var username = auth.split(":")[0];
var pass = auth.split(":")[1];

var remoteOptions = {
    user: 'yummy',
    password: 'candy,
    database: 'trinkets,
    charset: 'utf8',
    collation: 'utf8_general_ci',
    host: 'mysql.host.db.com',
    port: 3349
};

var sockOptions = {
    host: proxy.hostname,
    port: 1080,
    user: username,
    pass: pass
};

var sockConn = new SocksConnection(remoteOptions, sockOptions);

module.exports = {
    models: Path.normalize(__dirname + '/../models'),
    connections: {
		diskDb: {
		    adapter: 'disk'
		},
        mysql: {
            adapter: 'mysqlAdapter',
            stream: sockConn
        }
    },
    adapters: {
		disk: require('sails-disk'),
        mysqlAdapter: require('sails-mysql')
    }
};

But get Unhandled rejection [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Could not connect to MySQL:
Error: connect ECONNREFUSED whenever I attempt to connect. This is from a local machine however, not from Heroku (I wonder if that'd make any difference). I don't know how to console log out what the adapter is actually doing to see if things are going correctly. Any suggestions? Thanks for the help so far ;)

**Comment by dooburt** [comment]
Tried this variant also, same result:-

var Path = require('path'),
    url = require('url'),
    SocksConnection = require('socksjs');

var remoteOptions = {
    host: 'database.address.com'
};

var sockOptions = {
    host: 'us-east-1-static-brooks.quotaguard.com',
    port: 9293,
    user: 'quotaguarduser,
    pass: 'password'
};

var sockConn = new SocksConnection(remoteOptions, sockOptions);
module.exports = {
    models: Path.normalize(__dirname + '/../models'),
    connections: {
		diskDb: {
		    adapter: 'disk'
		},
        mysql: {
            adapter: 'mysqlAdapter',
            user: 'user',
            password: 'passie,
            database: 'trinkets',
            charset: 'utf8',
            collation: 'utf8_general_ci',
            port: 3349,
            stream: sockConn
        }
    },
    adapters: {
		disk: require('sails-disk'),
        mysqlAdapter: require('sails-mysql')
    }
};

**Comment by devinivy** [comment]
Just making sure– you can connect using that same `connections` configuration using the vanilla `sails-mysql` module?

**Comment by dooburt** [comment]
Yes, this:-

```
mysql: {
            adapter: 'mysqlAdapter',
            user: 'user',
            password: 'passie,
            database: 'trinkets',
            charset: 'utf8',
            collation: 'utf8_general_ci',
            port: 3349
        }
```
(with the correct credentials of course), works perfectly where the server IP address has been whitelisted.

**Comment by devinivy** [comment]
I mean, what happens when you try to connect to mysql using `mysql` package and `sockjs` package but not waterline?  I'm just trying to figure out if your connection issues are due to this adapter or due to your proxy connection.

**Comment by dooburt** [comment]
Hello there, sorry for the delay.  I never got this to work -- but I never confirmed it was not the proxy either. So I'm happy to close this. I found a way round it in the end (by not using a proxy), but my solution won't help anyone else, nor confirm if this could be a problem in sails-mysql.  Thank you for the help.
