### ISSUE TITLE
Select after update fails

### ISSUE THREAD

**Issue by rawrdrood** [balderdashy/sails-mysql#216]
When performing a PUT request to the api the update goes through but returns a 500 error.  The queries logged by the server are:

    255 Query     SELECT `eve`.`order_id`, `eve`.`type_id`, `eve`.`price`, `eve`.`qty_avail` FROM `items_buying` AS `eve`  WHERE `eve`.`order_id` = 2809443239  LIMIT 1
    255 Query     SELECT `eve`.`order_id`, `eve`.`type_id`, `eve`.`price`, `eve`.`qty_avail` FROM `items_buying` AS `eve`  WHERE `eve`.`order_id` = 2809443239
    255 Query     UPDATE `items_buying` AS `eve` SET `price` = 100, `qty_avail` = 200  WHERE `eve`.`order_id` = 2809443239
    255 Query     SELECT `eve`.`order_id`, `eve`.`type_id`, `eve`.`price`, `eve`.`qty_avail` FROM `items_buying` AS `eve`  WHERE `eve`.`id` = undefined  LIMIT 1

Model:
```
module.exports = {
  tableName: 'items_buying',
  autoPK: false,
  schema: true,
  autoCreatedAt: false,
  autoUpdatedAt: false, 
  attributes: {
	id: {  
		type: "integer",
		primaryKey: true,
		autoIncrement: true,
		unique: true,
		columnName: "order_id"
		
	},
	type_id: {
		type: "integer",
		columnName: "type_id"
	},
	price: { type: "float", columnName: "price" },
	qty_avail: { type: "float", columnName: "qty_avail" }
	
  }
  
  
};
```

**Comment by fjafferi** [comment]
+1
I've been dealing with this issue for last couple of days now.

**Comment by devinivy** [comment]
What version of waterline and sails-mysql are you using?

**Comment by fjafferi** [comment]
waterline: 0.10.19
sails-mysql: 0.11.0

**Comment by fjafferi** [comment]
Problem appears to be in this block of code:
```javascript
          var pk = 'id';
          Object.keys(collection.definition).forEach(function(key) {
            if(!collection.definition[key].hasOwnProperty('primaryKey')) return;
            pk = key;
          });
```
From what i can tell, "collection.definition" is an empty object.

**Comment by devinivy** [comment]
I highly suggest using a recent version of waterline.  0.10.19 is nearly half a year old, and there have been many fixes in the interim.

**Comment by fjafferi** [comment]
that did the trick, i guess i didn't realize that my waterline package was marked as not to update. Upgraded to 0.10.26 and it now works flawlessly.

Thank you!

**Comment by devinivy** [comment]
Great! :)
