### ISSUE TITLE
MySQL database connection timeout using AWS

### ISSUE THREAD

**Issue by maw87** [balderdashy/sails-mysql#226]
I am receiving a timeout error when sending a request to insert data into a table in my MySQL database hosted on Amazon (I am using a free micro instance).

I have set my connection options to be:

connectionName: {
     adapter: 'sails-mysql',
     host: '***',
     port: 3306,
     user: '***',
     password: '***',
     database: '***',
     connectionLimit: 100,
     acquireTimeout: 600000,
     connectTimeout: 600000,
     waitForConnections: true,
     pool: true,
     debug: true
   }

For the MySQL system variables containing "timeout", I have:

![captura de tela 2015-06-08 as 19 43 15](https://cloud.githubusercontent.com/assets/12566637/8047040/e5ed2ef2-0e16-11e5-8629-ace1c5dd3feb.png)

My connection times out consistently approximately 60 seconds after making the initial request, and I receive the following error:

![captura de tela 2015-06-08 as 19 28 31](https://cloud.githubusercontent.com/assets/12566637/8047036/dc2c3b06-0e16-11e5-83ab-7cbb3e2d0815.png)

**Comment by devinivy** [comment]
Your query.log should contain some info about what caused the timeout.  Given the timing your experiencing, maybe look into net_write_timeout.  Are you making any very large queries?

**Comment by maw87** [comment]
The query was simply inserting one line and the issue turned out to be simply that I needed to give outbound/inbound access to my VPC CIDR in the security group used for the RDS and VPC.

**Comment by devinivy** [comment]
Ah, thanks for coming back and letting us know!
