### ISSUE TITLE
How to keeping the exact value for a BigInteger

### ISSUE THREAD

**Issue by davidportella** [balderdashy/sails-mysql#231]
In node-mysql there the config options for biginteger these are: "supportBigNumbers" and "bigNumberStrings" which convert the number in a string and keep the exactitud of the number. How to configure this options (if it's available) in sails-msyql ?

**Comment by 2c2c** [comment]
doing research before I make any framework decisions. did this turn out to be an issue for you?

**Comment by particlebanana** [comment]
You should be able to pass this option in when you configure your connection. Make sure you set the attribute type as 'decimal'.
