### ISSUE TITLE
Primary Key int size diff from other integer data type.

### ISSUE THREAD

**Issue by kamote** [balderdashy/sails-mysql#232]
<code>
 `id` INT(10)  UNSIGNED  NOT NULL  AUTO_INCREMENT
</code>
while the other integer type are 
<code>
 `other_id` INT(11)  NOT NULL  AUTO_INCREMENT
</code>

I manually remove UNSIGNED
from
<code>
return attrName + ' INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
</code>

to
<code>
return attrName + ' INT NOT NULL AUTO_INCREMENT PRIMARY KEY';
</code>

It will now generate proper int size, because I need it in the relation of tables
<code>
 `id` INT(11)  NOT NULL  AUTO_INCREMENT
</code>
while the other integer type are 
<code>
 `other_id` INT(11)  NOT NULL  AUTO_INCREMENT
</code>

**Comment by devinivy** [comment]
The `10` versus `11` is simply the display width of the number.  An unsigned integer needs one less character for max display width because it doesn't need to account for the requisite `-` character.  See: http://stackoverflow.com/questions/5256560/mysql-datatype-int11-whereas-unsigned-int10 .
