### ISSUE TITLE
ER_ROW_IS_REFERENCED when lifting sails in drop mode

### ISSUE THREAD

**Issue by kamsi** [balderdashy/sails-mysql#243]
I get:

`error: Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails`

This happens because `sails-mysql` tries to drop a table before it dropped a table with a foreign key.

**Comment by devinivy** [comment]
Do you have any suggestions how to deal with this?

**Comment by kamsi** [comment]
@devinivy on idea which comes to me would be to be to check for a constraints:

`USE information_schema;
SELECT *
FROM
  KEY_COLUMN_USAGE
WHERE
  REFERENCED_TABLE_NAME = 'name_of_table_to_check';`

This should supply info about which tables need to be removed first.

**Comment by devinivy** [comment]
Thanks!  It's useful to know where that lives in the information shema.  Then perhaps we would use a [topo](https://github.com/hapijs/topo)-sort to determine the order in which the tables should be dropped.

**Comment by kamsi** [comment]
@devinivy I came up with a simpler idea.
Before you run `DROP` commands, do:
`SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;`
and after that you just do:
`SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;`

**Comment by devinivy** [comment]
Love it.  If you have the time to create a PR, I'd enjoy taking a look.  Would go roughly here: https://github.com/balderdashy/sails-mysql/blob/2441e4601618263700cf9ccd190acc42b9a1cab2/lib/adapter.js#L245.

A failing unit test would be a nice step too!

**Comment by kamsi** [comment]
@devinivy I can try to implement this solution, however I believe that I shouldn't mess with the drop function itself. This FK constraint is there on purpose, I should rather switch off the FK check before the model building script starts, and bring those checks back after it's finished...

**Comment by devinivy** [comment]
Alright.  Perhaps we could at least make a note of this approach in the docs.

**Comment by kamsi** [comment]
@devinivy yes, I think it was a misunderstanding, it should be something that goes with a setup script. I thought I could create my models from db during the lift... but from what I gather now this feature is not yet available. My problem should be solved in the context of such a script. It was my first contact with sails, so I was a bit lost. Sorry for the false alarm.

**Comment by devinivy** [comment]
No worries– thanks for coming-up with this approach!  We'll offer it as a suggestion to those facing similar issues in the future.
