### ISSUE TITLE
Slow due to usage of MySQLs LOWER() on string fields

### ISSUE THREAD

**Issue by erkstruwe** [balderdashy/sails-mysql#255]
Hi there,

this adapter uses MySQLs LOWER() function on string fields for case insensititvity e.g. in a SELECT... WHERE... statement. This has a huge impact on the performance of large tables because every single row's attribute has to be converted to lowercase to perform the WHERE check and indexes cannot be used.

Example:
SELECT ... FROM user WHERE LOWER(user.name) = "foo"
is way slower than
SELECT ... FROM user WHERE user.name = "foo"

Since any DB field in MySQL can be used in a case-insensitive collation, why is this needed in the first place?

**Comment by devinivy** [comment]
Good question!  I defer to @particlebanana and the original module writers in this case.  It does seem like using a case-insensitive collation would be the best way to do this.

**Comment by erkstruwe** [comment]
Workaround is to include the attribute `wlNext: {caseSensitive: true}` into `sqlOptions` in `adapter.js`.

**Comment by santec** [comment]
With LOWER(), MySQL cannot use indexes. Not an acceptable limitation for non-trivial applications or non-trivial amount of data.
If you want to make all searches case-insensitive (which is wrong, anyway) you can use LIKE.

**Comment by particlebanana** [comment]
Answered in another thread. @santec by default all searches in MySql are case-insensitive unless the collation has been changed.

https://github.com/balderdashy/sails/issues/3304#issuecomment-148780960
