### ISSUE TITLE
MySQL 5.7.8 JSON datatype

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails-mysql#270]
Upstream comment:

https://github.com/felixge/node-mysql/issues/1327

**Comment by RWOverdijk** [comment]
Nice. :) That would be cool

**Comment by particlebanana** [comment]
Would be great to get a query builder that could somehow work with the postgres json query stuff and mysql. 

If you would like to make a [proposal](https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements) to the Waterline roadmap with what this might look like when they get it implemented that would be great!
